config/routes.rb
SimpleTwitter::Application.routes.draw do
  
  resources :users, :only => [:show, :index]
  
  resources :tweets, :only => [:create, :destroy]
  post 'more' => 'tweets#more', :as => :more_tweets
  
  resources :relationships, :only => [:destroy, :update]
  
  devise_for :users, :controllers => { :sessions => :sessions,
                                       :registrations => :registrations },
                     :skip => [:sessions] do
    get 'signin' => 'sessions#new', :as => :new_user_session
    post 'signin' => 'sessions#create', :as => :user_session
    get 'signout' => 'sessions#destroy', :as => :destroy_user_session
    
    get 'signup' => 'registrations#new', :as => :new_user_registration
    post 'signup' => 'registrations#create', :as => :user_registration
    get 'edit' => 'registrations#edit', :as => :edit_user_registration
    put 'signup' => 'registrations#update'
    
    get 'users/show' => 'users#show', :as => :user_root
  end
  
  devise_scope :user do 
    root :to => "sessions#new"
    get 'confirmation' => 'devise/confirmations#show', 
  end
  

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  
  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"
  
  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
  
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  belongs_to :user
  
  validates :content, :presence => true,
                      :length =>  {:maximum => 140}
  validates :user,    :presence => true
  
  class << self
    def per_page
      10
    end
  end
  
  default_scope :order => 'tweets.created_at DESC'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :encryptable, :confirmable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  
  has_many :tweets
  has_many :relationships, :foreign_key => "follower_id"
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship"
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships, :source => :follower
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include TweetsHelper
  include UsersHelper
end

app/controllers/registrations_controller.rb
class RegistrationsController  < Devise::RegistrationsController
  
  def create
    if verify_recaptcha
      super
    else
      build_resource
      clean_up_passwords(resource)
      flash[:alert] = "There was an error with the recaptcha code below. Please re-enter the code and click submit."
      #render_with_scope :new
      render :new
    end
  end

  def new
    if user_signed_in?
      redirect_to current_user
    else
      super
    end
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :authenticate_user!
  
  def update
    user = User.find_by_id params[:id]
    current_user.follow!(user)
    redirect_to user_path(user),
                :flash => { :notice => "You have successfully followed user #{user.email}" }
  end
  
  def destroy
    user = User.find_by_id params[:id]
    current_user.unfollow!(user)
    redirect_to user_path(user),
                :flash => { :notice => "You have successfully unfollowed user #{user.email}" }
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  
  def new
    if user_signed_in?
      redirect_to current_user
    else
      super
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @tweet = Tweet.new(params[:tweet])
    @tweet.user = current_user
    @tweet.save
  end
  
  def more
    page_of_tweets(params)
  end
  
  def destroy
    Tweet.destroy(params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @user = User.find_by_id(params[:id]) || current_user
    @tweet = Tweet.new
    page_of_tweets(params)
  end
  
  def index
    @users = User.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  
  def page_of_tweets(params)
    params[:page] = 0 if params[:page].nil?
    @page = params[:page].to_i
    limit = Tweet.per_page
    offset = @page * limit
    
    # Brute force!!!
    params[:user_id] = current_user.id if params[:user_id].nil?
    user = User.find_by_id(params[:user_id])
    ids = [current_user.id]
    user.following.each do |followed|
      ids << followed.id
    end
    
    @tweets = Tweet.find_all_by_user_id(ids, :offset => offset, :limit => limit)
    
    if @tweets.last == Tweet.find_last_by_user_id(ids)
      @page = -1
    end
      @page = @page + 1
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 64})
    gravatar_image_tag user.email, :alt => user.email,
                                   :id => "avatar",
                                   :class => 'avatar',
                                   :gravatar => options
  end
  
end

app/views/layouts/_delete_tweet.erb
<%= link_to "Delete", tweet, :remote => true, :method => :delete,
                             :class => 'delete' %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_gravatar.erb
<%= gravatar_image_tag user.email, :alt => user.email, :id => "avatar",
                                   :class => 'avatar' %>

app/views/layouts/_head.html.erb
<div class="section">
  <div class="span-1 prepend-16">
    <%= link_to 'Home', current_user %>
  </div>
  <div class="span-2 last">
    <%= link_to "Sign out", destroy_user_session_path %>
  </div>
</div>

app/views/layouts/_left_side.html.erb
<div class="span-12 border">
  <%= render 'users/information' %>
  <%= render 'tweets/form' %>
  <%= render 'layouts/tweets' %>
</div>

app/views/layouts/_right_side.html.erb
<div class="prepend-1 span-11 last">
  <%= render 'layouts/who_to_follow' %>
  <%= render 'users/followers' %>
  <%= render 'users/followeds' %>
</div>

app/views/layouts/_tweets.html.erb
<div class="span-12">
  <div id="tweets">
    <%= render 'tweets/list' %>
  </div>
  <% if @page > 0 %>
    <%= render 'tweets/more_tweets' %>
  <% end %>
</div>

app/views/layouts/_who_to_follow.html.erb
<div class="span-11 middle">
  <%= link_to "Who to follow", users_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTwitter</title>
    <%= stylesheet_link_tag    'blueprint/screen', 'application', 'styles' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/head' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<% if @user == current_user %>
  <div class="span-12">
    <div class="big">What’s happening?</div>
    <%= form_for(@tweet, :remote => true) do |f| %>
      <div class="field">
        <%= f.label :content, :class => "hack",
                              :style => "display:none; margin:0px; padding:0px;" %>
        <%= f.text_area :content, :rows => 8 %>
      </div>
      <div class="actions">
        <%= f.submit "Tweet" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tweets/_list.html.erb
<% @tweets.each do |tweet| %>
  <%= render :partial => 'tweets/tweet', :locals => { :tweet => tweet } %>
<% end %>

app/views/tweets/_more_tweets.erb
<div id="tweets-more">
  <%= form_for(:pagination, :remote => true, :url => more_tweets_path ) do |f| %>
    <%= f.hidden_field :page, :name => :page, :value => @page %>
    <%= f.hidden_field :user_id, :name => :user_id, :value => @user.id %>
    <div class="actions">
      <%= f.submit "More" %>
    </div>
  <% end %>
</div>

app/views/tweets/_tweet.html.erb
<div class="tweet round">
  <div class="section">
    <div class="span-1">
      <%= gravatar_for tweet.user, :size => 32 %>
    </div>
    <div class="span-10 last middle">
      <%= link_to tweet.user.email, tweet.user %>
    </div>
  </div>
  <div class="content">
    <%= tweet.content %>
  </div>
  <div class="time">
    <%= tweet.created_at %>
  </div>
  <% if tweet.user == current_user %>
  <div>
    <%= render :partial => 'layouts/delete_tweet', :locals => { :tweet => tweet } %>
  </div>
  <% end %>
</div>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/create.js.erb
<% if @tweet.errors.any? %>
  alert("Error : content " + "<%= escape_javascript(@tweet.errors[:content].first) %>");
<% else %>
  $('#tweets').prepend("<%= escape_javascript(render :partial => 'tweets/tweet',
                                          :locals => { :tweet => @tweet }) %>");
  $('textarea').val('');
<% end %>

app/views/tweets/more.js.erb
$('#tweets').append("<%= escape_javascript(render :partial => 'tweets/list',
                                          :locals => { }) %>");
<% if @page > 0 %>
  $('#tweets-more').find('input[name="page"]').val("<%= @page %>");
<% else %>
  $('#tweets-more').remove();
<% end %>

app/views/users/_follow-unfollow.erb
<% if current_user.following?(@user) %>
  <%= link_to "Unfollow", relationship_path(@user.id), :method => :delete %>
<% else %>
  <%= link_to "Follow", relationship_path(@user.id), :method => :put %>
<% end %>

app/views/users/_followeds.erb
<% if @user.following.any? %>
  <div id="followeds" class="span-12 last">
    <div class="middle">
      <%= pluralize(@user.following.count, 'followed') %>
    </div>
    <% @user.following.each do |followed| %>
      <div class="section">
        <div class="span-1">
          <%= gravatar_for followed, :size => 32 %>
        </div>
        <div class="span-11 last middle">
          <%= link_to followed.email, followed %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_followers.erb
<% if @user.followers.any? %>
  <div id="followers" class="span-12 last">
    <div class="middle">
      <%= pluralize(@user.followers.count, 'follower') %>
    </div>
    <% @user.followers.each do |follower| %>
      <div class="section">
        <div class="span-1">
          <%= gravatar_for follower, :size => 32 %>
        </div>
        <div class="span-11 last middle">
          <%= link_to follower.email, follower %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_information.html.erb
<div class="span-2">
  <%= gravatar_for @user %>
</div>
<div class="span-10 last">
  <div class="big email"><%= @user.email %></div>
  <% if @user == current_user %>
    <%= link_to "Edit profile", edit_user_registration_path %>
  <% else %>
    <%= render 'users/follow-unfollow' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>List of users</h1>

<% @users.each do |user| %>
  <% if user.id != current_user.id and user.confirmed? and not current_user.following?(user) %>
  <div class="section">
    <div class="span-2 prepend-8"><%= gravatar_for user %></div>
    <div class="span-8 big"><%= link_to user.email, user, :class => "email" %></div>
  </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/left_side' %>
<%= render 'layouts/right_side' %>